const { chromium } = require('@playwright/test')
;(async () => {
  const browser = await chromium.launch()
  const context = await browser.newContext()
  const page = await context.newPage()
  page.on('console', (msg) => console.log('console>', msg.type(), msg.text()))
  page.on('pageerror', (err) => console.error('pageerror>', err))
  await page.goto('http://localhost:3000/register')
  await page.fill('input[name="firstName"]', 'Debug')
  await page.fill('input[name="lastName"]', 'Test')
  const email = `direct-${Date.now()}@assetflow.test`
  await page.fill('input[name="email"]', email)
  await page.fill('input[name="password"]', 'AdminPass123!')
  await page.fill('input[name="organizationName"]', 'Debug Org')
  await Promise.all([
    page.waitForURL(/\/onboarding/, { timeout: 60000 }),
    page.click('button:has-text("Create Account")'),
  ])
  await page.waitForTimeout(1000)
  console.log('localStorage after register', await page.evaluate(() => JSON.stringify({ keys: Object.keys(localStorage), auth: localStorage.getItem('assetflow-auth') })))
  console.log('cookies after register', await page.evaluate(() => document.cookie))
  await page.click('button:has-text("Manufacturing")')
  await page.click('button:has-text("Multiple locations")')
  await page.click('button:has-text("Save and Continue")')
  await page.click('button:has-text("₦500,000")')
  await page.click('button:has-text("Straight Line")')
  await page.click('button:has-text("Save and Continue")')
  await page.fill('input[placeholder="Branch 1 name"]', 'Lagos Head Office')
  await page.fill('input[placeholder="Code (e.g. HQ)"]', 'LHO')
  await page.click('button:has-text("Add another branch")')
  await page.fill('input[placeholder="Branch 2 name"]', 'Abuja Office')
  await page.fill('input[placeholder="Code (e.g. HQ)"]', 'ABJ')
  await page.click('button:has-text("Save and Continue")')
  console.log('before goto import url', page.url())
  await page.goto('http://localhost:3000/assets/import?from=onboarding', { waitUntil: 'load', timeout: 60000 })
  console.log('after goto import url', page.url())
  await page.waitForFunction(() => document.readyState === 'complete', { timeout: 60000 })
  await page.waitForTimeout(5000)
  console.log('localStorage on import', await page.evaluate(() => JSON.stringify({ keys: Object.keys(localStorage), auth: localStorage.getItem('assetflow-auth') })))
  console.log('cookies on import', await page.evaluate(() => document.cookie))
  console.log('loading text count', await page.locator('text=Loading...').count())
  console.log('heading count', await page.locator('text=Import your asset register').count())
  console.log('body child count', await page.evaluate(() => document.body.children.length))
  console.log('body child tags', await page.evaluate(() => Array.from(document.body.children).map((el) => el.tagName + (el.id ? `#${el.id}` : '')).join(', ')))
  console.log('first body child outerHTML', await page.evaluate(() => document.body.children[0]?.outerHTML?.slice(0, 600)))
  console.log('section outerHTML', await page.evaluate(() => Array.from(document.body.querySelectorAll('section')).map((el) => el.outerHTML.slice(0, 600)).join('\n---\n')))
  await page.screenshot({ path: 'debug-import-direct.png', fullPage: true })
  await browser.close()
})().catch((err) => {
  console.error(err)
  process.exit(1)
})
